
version: '2.1'

services:
  gobgp_control:
   build:
     context: ./
     dockerfile: Dockerfile-control
   volumes:
       - ../:/gobgprest
   ports:
       - "8080:8080"
   networks:
     test_net:
        ipv4_address: 10.0.255.10
  gobgp_1:
    build:
      context: ./
      dockerfile: Dockerfile-gobgp
    command: "-f configs/gobgpd_1.conf"
    networks:
      test_net:
        ipv4_address: 10.0.255.2
  gobgp_2:
    build:
      context: ./
      dockerfile: Dockerfile-gobgp
    command: "-f configs/gobgpd_2.conf"
    networks:
      test_net:
        ipv4_address: 10.0.255.3
networks:
  test_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.0.255.0/24
